const x = 10;

try {
    
    x = 1;

} catch (err) {
    console.log(`Erro ${err}`);
}
